name: csi-driver-lvm
version: 0.3.7
description: local persistend storage for lvm
appVersion: v0.3.7
apiVersion: v1
keywords:
- storage
- block-storage
- volume
home: https://metal-stack.io
sources:
- https://github.com/metal-stack
