{{- if .Values.rbac.pspEnabled }}

apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp-lvm-{{ .Release.Name }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  allowPrivilegeEscalation: true
  fsGroup:
    rule: RunAsAny
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp-lvm-role
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - psp-lvm-{{ .Release.Name }}
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-rolebinding-lvm
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp-lvm-role
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: csi-lvm-attacher
- apiGroup: ""
  kind: ServiceAccount
  name: csi-lvm
- apiGroup: ""
  kind: ServiceAccount
  name: csi-lvm-provisioner
- apiGroup: ""
  kind: ServiceAccount
  name: csi-lvm-resizer
- apiGroup: ""
  kind: ServiceAccount
  name: csi-lvm-snapshotter
- apiGroup: ""
  kind: ServiceAccount
  name: csi-lvm-socat
- apiGroup: ""
  kind: ServiceAccount
  name: csi-attacher
- apiGroup: ""
  kind: ServiceAccount
  name: csi-provisioner
- apiGroup: ""
  kind: ServiceAccount
  name: csi-resizer
- apiGroup: ""
  kind: ServiceAccount
  name: csi-snapshotter
- apiGroup: ""
  kind: ServiceAccount
  name: csi-lvmplugin

{{- end }}
