
lvm:
  devicePattern: /dev/nvme[0-9]n[0-9]
  vgName: csi-lvm

pluginImage:
  repository: mwennrich/lvmplugin
  tag: v0.1.2
  pullPolicy: IfNotPresent

provisionerImage:
  repository: mwennrich/csi-lvmplugin-provisioner
  tag: v0.1.2
  pullPolicy: IfNotPresent

rbac:
  create: true
  pspEnabled: true
